/********************************************************************************
This file is part of ShoX.

ShoX is free software; you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any later version.

ShoX is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with 
ShoX; if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
Fifth Floor, Boston, MA 02110-1301, USA

Copyright 2006 The ShoX developers as defined under http://shox.sourceforge.net
********************************************************************************/

package br.ufla.dcc.grubix.simulator.event;

import br.ufla.dcc.grubix.simulator.Address;
import br.ufla.dcc.grubix.simulator.NodeId;

/**
 * Super-class of all packets generated by the NetworkLayer. This is to ensure some
 * basic information to be present in all network packets regardless of the particular
 * implementation of the network layer, so lower layers can make use of it.
 * @author jlsx
 */
public class NetworkPacket extends Packet {

	/**
	 * Default constructor of class Packet to create a terminal packet
	 * with no enclosed packet.
	 * @param sender Senderaddress of the packet
	 * @param receiver ReceiverId of the packet
	 */
	public NetworkPacket(Address sender, NodeId receiver) {
		super(sender, receiver);
	}
	
	/**
	 * Overloaded constructor to create non-terminal packets by
	 * specifying a packet to enclose.
	 * ReceiverID of the new packet taken from enclosedPacket.
	 * 
	 * @param sender Senderaddress of the packet
	 * @param packet The packet to enclose inside the new packet.
	 */
	public NetworkPacket(Address sender, Packet packet) {
		super(sender, packet);
	}
	
	/**
	 * Overloaded constructor to create non-terminal packets by
	 * specifying a packet to enclose.
	 * ReceiverID of the new packet may not be the same as stated in the enclosedPacket.
	 * 
	 * @param sender Senderaddress of the packet
	 * @param receiver ReceiverId of the packet
	 * @param packet The packet to enclose inside the new packet.
	 */
	public NetworkPacket(Address sender, NodeId receiver, Packet packet) {
		super(sender, receiver, packet);
	}

	/**
	 * This method returns the NodeId of the receiver of the innermost enclosed NetworkPacket.
	 * @return the NodeId of the receiver of the innermost enclosed NetworkPacket
	 */
	public NodeId getFinalNetworkPacketReceiver() {
		Packet enclosedPacket2 = this.getEnclosedPacket();

		if (enclosedPacket2 != null && enclosedPacket2 instanceof NetworkPacket) {
			NetworkPacket tmpPacket = (NetworkPacket) enclosedPacket2;
			return tmpPacket.getFinalNetworkPacketReceiver();
		} else {
			return this.getReceiver();
		}
	}
	
	/**
	 * This method returns the NodeId of the sender of the innermost enclosed NetworkPacket.
	 * @return the NodeId of the sender of the innermost enclosed NetworkPacket
	 */
	public NodeId getInitialNetworkPacketSender() {
		Packet enclosedPacket2 = this.getEnclosedPacket();

		if (enclosedPacket2 != null && enclosedPacket2 instanceof NetworkPacket) {
			NetworkPacket tmpPacket = (NetworkPacket) enclosedPacket2;
			return tmpPacket.getInitialNetworkPacketSender();
		} else {
			return this.getSender().getId();
		}
	}
}
